apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: issue
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 5000m
            memory: 5Gi
