apiVersion: v1
kind: Pod
metadata:
  name: unhealthy-app
spec:
  containers:
  - name: app
    image: unhealthy-app-image
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5