apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - ""
  resources:
  - secrets 
  verbs:
  - 'get'